CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS families (id uuid PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE, name text NOT NULL, role text NOT NULL CHECK (role IN ('admin','adult','child')), email text UNIQUE NOT NULL, password_hash text NOT NULL, is_child_account boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS family_members (id uuid PRIMARY KEY, family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE, name text NOT NULL, relationship text NOT NULL, is_deceased boolean NOT NULL DEFAULT false, posthumous_status text NOT NULL DEFAULT 'authorization_requested', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memories (id uuid PRIMARY KEY, family_member_id uuid NOT NULL REFERENCES family_members(id) ON DELETE CASCADE, uploader_id uuid NOT NULL REFERENCES users(id), type text NOT NULL CHECK (type IN ('photo','video','audio','text','doc')), title text NOT NULL, storage_path text, original_name text, mime_type text, transcript text, tags jsonb NOT NULL DEFAULT '[]', consent_status text NOT NULL DEFAULT 'pending' CHECK (consent_status IN ('pending','approved','rejected')), processing_status text NOT NULL DEFAULT 'processing', processed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memory_embeddings (id uuid PRIMARY KEY, memory_id uuid NOT NULL REFERENCES memories(id) ON DELETE CASCADE, chunk_text text NOT NULL, embedding vector(8), metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS consent_records (id uuid PRIMARY KEY, family_member_id uuid NOT NULL REFERENCES family_members(id) ON DELETE CASCADE, type text NOT NULL, granted_by uuid NOT NULL REFERENCES users(id), granted_at timestamptz NOT NULL DEFAULT now(), legal_basis text, revoked_at timestamptz);
CREATE TABLE IF NOT EXISTS voice_models (id uuid PRIMARY KEY, family_member_id uuid NOT NULL REFERENCES family_members(id) ON DELETE CASCADE, source_memory_id uuid NOT NULL REFERENCES memories(id), consent_record_id uuid NOT NULL REFERENCES consent_records(id), model_path text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id uuid PRIMARY KEY, family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), family_member_id uuid NOT NULL REFERENCES family_members(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY, conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, role text NOT NULL, content text NOT NULL, source_memory_ids jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_log (id uuid PRIMARY KEY, family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE, actor_id uuid REFERENCES users(id), action text NOT NULL, target_type text NOT NULL, target_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
